version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci || npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - 'dist/my-angular-project/**/*'
    - 'appspec.yml'
    - 'deploy-scripts/**/*'

